In [26]:
import pandas as pd
from datetime import date
# --- DataFrame 1: Funcionários ---
data_funcionarios = {
"ID_Funcionario": [101, 102, 103, 104, 105, 106, 107, 108],
"Nome": ["Ana", "Bruno", "Carla", "Daniel", "Elisa", "Fábio", "Gabriela", "Hugo"],
"Sobrenome": ["Silva", "Costa", "Oliveira", "Souza", "Pereira", "Martins", "Alves", "Ribeiro"],
"ID_Departamento": [1, 2, 1, 3, 2, 1, 3, 2],
"ID_Cargo": [10, 11, 12, 13, 11, 10, 14, 12],
"Data_Contratacao": pd.to_datetime(["2022-01-15", "2021-05-30", "2022-03-10", "2020-11-01", "2023-07-20",
"2022-02-18", "2021-09-05", "2023-11-01"])
}

df_funcionarios = pd.DataFrame(data_funcionarios)
# --- DataFrame 2: Departamentos ---
data_departamentos = {
"ID_Departamento": [1, 2, 3, 4],
"Nome_Departamento": ["Engenharia", "Marketing", "RH", "Financeiro"],
"Localizacao": ["Andar 10", "Andar 8", "Andar 9", "Andar 9"]
}

df_departamentos = pd.DataFrame(data_departamentos)
# --- DataFrame 3: Cargos e Salários ---
data_cargos_salarios = {
"ID_Cargo": [10, 11, 12, 13, 14, 15],
"Nome_Cargo": ["Eng. Software Jr", "Analista de Marketing", "Eng. Software Sr", "Gerente de Contas",
"Recrutador", "Analista Financeiro"],
"Salario_Base": [5500, 6000, 9500, 8000, 5000, 7000],
"Nivel": ["Junior", "Pleno", "Senior", "Pleno", "Junior", "Pleno"]
}

df_cargos_salarios = pd.DataFrame(data_cargos_salarios)
# --- DataFrame 4: Projetos ---
data_projetos = {
"ID_Projeto": ["P-1001", "P-1002", "P-1003"],
"Nome_Projeto": ["Sistema de Login", "Campanha de Natal", "Otimização de Performance"],
"ID_Gerente_Projeto": [103, 104, 103],
"Status": ["Em Andamento", "Planejamento", "Concluído"]
}
df_projetos = pd.DataFrame(data_projetos)
# --- DataFrame 5: Alocação de Horas ---
data_alocacao = {
"ID_Alocacao": [1, 2, 3, 4, 5, 6, 7],
"ID_Funcionario": [101, 103, 107, 102, 105, 101, 108],
"ID_Projeto": ["P-1001", "P-1001", "P-1003", "P-1002", "P-1002", "P-1003", "P-1002"],

"Horas_Semanais_Alocadas": [20, 40, 30, 25, 15, 10, 40]
}
df_alocacao = pd.DataFrame(data_alocacao)

In [ ]:
# --- Exercicio 1 ---

df_func_dpto = pd.merge(df_funcionarios, df_departamentos, on = "ID_Departamento")
display(df_func_dpto)

# --- Exercicio 2 ---

df_func_salario = pd.merge(df_funcionarios, df_cargos_salarios, on="ID_Cargo")
display(df_func_salario)

# --- Exercicio 3 ---

df_alocacao_completa1 = pd.merge(df_alocacao, df_funcionarios, on="ID_Funcionario")
df_alocacao_completa = pd.merge(df_alocacao_completa1, df_projetos, on="ID_Projeto")

display(df_alocacao_completa)

# --- Exercicio 4 ---

df_medias_salarios1 = pd.merge(df_funcionarios, df_departamentos, on = "ID_Departamento")
df_medias_salarios = pd.merge(df_medias_salarios1, df_cargos_salarios, on="ID_Cargo")

mediaSalario = df_medias_salarios.groupby("Nome_Departamento")["Salario_Base"].mean()
display(mediaSalario.round(2).reset_index())

# --- Exercicio 5 ---

totalFuncCargos = df_func_salario.groupby("Nivel").size()
display(totalFuncCargos.reset_index())

# --- Exercicio 6 ---

df_aloc_proj = pd.merge(df_alocacao, df_projetos, on="ID_Projeto")
totalHoras = df_aloc_proj.groupby("Nome_Projeto")["Horas_Semanais_Alocadas"].sum()
display(totalHoras.reset_index())

# --- Exercicio 7 ---

funcEng = df_func_dpto[df_func_dpto["Nome_Departamento"] =="Engenharia"]
display(funcEng)

# --- Exercicio 8 ---

projAndamento = df_projetos[df_projetos["Status"] =="Em Andamento"]
display(projAndamento)

# --- Exercicio 9 ---

funJan = df_funcionarios[df_funcionarios["Data_Contratacao"] < "2022-01-01"]
display(funJan)

,ID_Funcionario,Nome,Sobrenome,ID_Departamento,ID_Cargo,Data_Contratacao,Nome_Departamento,Localizacao
0,101,Ana,Silva,1,10,2022-01-15,Engenharia,Andar 10
1,102,Bruno,Costa,2,11,2021-05-30,Marketing,Andar 8
2,103,Carla,Oliveira,1,12,2022-03-10,Engenharia,Andar 10
3,104,Daniel,Souza,3,13,2020-11-01,RH,Andar 9
4,105,Elisa,Pereira,2,11,2023-07-20,Marketing,Andar 8
5,106,Fábio,Martins,1,10,2022-02-18,Engenharia,Andar 10
6,107,Gabriela,Alves,3,14,2021-09-05,RH,Andar 9
7,108,Hugo,Ribeiro,2,12,2023-11-01,Marketing,Andar 8

,ID_Funcionario,Nome,Sobrenome,ID_Departamento,ID_Cargo,Data_Contratacao,Nome_Cargo,Salario_Base,Nivel
0,101,Ana,Silva,1,10,2022-01-15,Eng. Software Jr,5500,Junior
1,102,Bruno,Costa,2,11,2021-05-30,Analista de Marketing,6000,Pleno
2,103,Carla,Oliveira,1,12,2022-03-10,Eng. Software Sr,9500,Senior
3,104,Daniel,Souza,3,13,2020-11-01,Gerente de Contas,8000,Pleno
4,105,Elisa,Pereira,2,11,2023-07-20,Analista de Marketing,6000,Pleno
5,106,Fábio,Martins,1,10,2022-02-18,Eng. Software Jr,5500,Junior
6,107,Gabriela,Alves,3,14,2021-09-05,Recrutador,5000,Junior
7,108,Hugo,Ribeiro,2,12,2023-11-01,Eng. Software Sr,9500,Senior

,ID_Alocacao,ID_Funcionario,ID_Projeto,Horas_Semanais_Alocadas,Nome,Sobrenome,ID_Departamento,ID_Cargo,Data_Contratacao,Nome_Projeto,ID_Gerente_Projeto,Status
0,1,101,P-1001,20,Ana,Silva,1,10,2022-01-15,Sistema de Login,103,Em Andamento
1,2,103,P-1001,40,Carla,Oliveira,1,12,2022-03-10,Sistema de Login,103,Em Andamento
2,3,107,P-1003,30,Gabriela,Alves,3,14,2021-09-05,Otimização de Performance,103,Concluído
3,4,102,P-1002,25,Bruno,Costa,2,11,2021-05-30,Campanha de Natal,104,Planejamento
4,5,105,P-1002,15,Elisa,Pereira,2,11,2023-07-20,Campanha de Natal,104,Planejamento
5,6,101,P-1003,10,Ana,Silva,1,10,2022-01-15,Otimização de Performance,103,Concluído
6,7,108,P-1002,40,Hugo,Ribeiro,2,12,2023-11-01,Campanha de Natal,104,Planejamento

  Nome_Departamento  Salario_Base
0        Engenharia       6833.33
1         Marketing       7166.67
2                RH       6500.00

    Nivel  0
0  Junior  3
1   Pleno  3
2  Senior  2

                Nome_Projeto  Horas_Semanais_Alocadas
0          Campanha de Natal                       80
1  Otimização de Performance                       40
2           Sistema de Login                       60

,ID_Funcionario,Nome,Sobrenome,ID_Departamento,ID_Cargo,Data_Contratacao,Nome_Departamento,Localizacao
0,101,Ana,Silva,1,10,2022-01-15,Engenharia,Andar 10
2,103,Carla,Oliveira,1,12,2022-03-10,Engenharia,Andar 10
5,106,Fábio,Martins,1,10,2022-02-18,Engenharia,Andar 10

  ID_Projeto      Nome_Projeto  ID_Gerente_Projeto        Status
0     P-1001  Sistema de Login                 103  Em Andamento

,ID_Funcionario,Nome,Sobrenome,ID_Departamento,ID_Cargo,Data_Contratacao
1,102,Bruno,Costa,2,11,2021-05-30
3,104,Daniel,Souza,3,13,2020-11-01
6,107,Gabriela,Alves,3,14,2021-09-05